"""The Notion project catalogue, read through the sentinel's own loader.

`data/projects.json` is generated by `sentinel sync-projects` from Notion's
Projects database and is the operational source of truth for what projects
exist. This adapter READS it and never writes it -- the file's own header says
"Do not hand-edit; re-run instead", and the graph has no business being the
exception.

Facts from here are ASSERTED: Notion said project X carries permit Y. They are
not inferences and must not be recorded as though they were.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterator

from .base import SourceRecord, utc_stamp

DEFAULT_PATH = (Path(__file__).resolve().parents[2]
                / "apps/email-sentinel/data/projects.json")


class ProjectsJson:
    """Adapter over the synced project catalogue."""

    name = "projects_json"

    def __init__(self, path: str | Path = DEFAULT_PATH, limit: int | None = None) -> None:
        self.path = Path(path)
        self.limit = limit

    def records(self) -> Iterator[SourceRecord]:
        from .._reuse import projects_loader
        load = projects_loader()
        projects = load(self.path)
        if self.limit is not None:
            projects = projects[: self.limit]
        observed = utc_stamp(None)
        for project in projects:
            yield SourceRecord(
                kind="project",
                source=self.name,
                source_ref=f"{self.path.name}#{project.project_id}",
                observed_at=observed,
                payload={
                    "project_id": project.project_id,
                    "name": project.name,
                    "address": project.address,
                    "apn": project.apn,
                    "permit_numbers": list(project.permit_numbers),
                    "client_emails": list(project.client_emails),
                    "stage": project.stage,
                    "notion_page_id": project.notion_page_id,
                    "drive_url": project.drive_url,
                })
