"""Match a jurisdiction permit CSV export against our project registry.

    python3 tools/match_permits.py <export.csv> [--projects PATH] [--all]

Portal exports are noisy -- searching by house number alone returns every
street with that number. This keeps only the rows that belong to a project in
projects.json, matched on parcel number first and street address second, and
reports which of our projects the export did not cover.

Reads only. Never writes to projects.json (that file is generated by
`sentinel sync-projects`; re-run the sync instead of editing it).
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path

DEFAULT_PROJECTS = Path(__file__).resolve().parents[1] / "apps/email-sentinel/data/projects.json"
SHOW = ("Permit Number", "Permit Work Type", "Permit Name", "Status",
        "Total Fees", "Total Payments", "Issued Start Date", "Expiration Date",
        "Completion Date", "Registered Contractor Name")

DIRECTIONS = {"N","S","E","W","NE","NW","SE","SW"}
SUFFIXES = {"ST","AVE","DR","RD","LN","PL","CT","BLVD","WAY","CIR","TRL","PKWY",
            "LOOP","TER","HWY","PKY","AVENUE","STREET","DRIVE","ROAD","LANE","PLACE"}


def norm_apn(value: str) -> str:
    return re.sub(r"[^0-9A-Z]", "", (value or "").upper())


def make_key(number, direction, name, suffix):
    """Street identity. Suffix and direction are part of it -- 12TH ST and
    12TH PL are different streets and must not collide."""
    num = re.sub(r"\D", "", number or "")
    nm = " ".join(t for t in re.split(r"[^0-9A-Z]+", (name or "").upper()) if t)
    if not (num and nm):
        return None
    return (num, (direction or "").upper().strip(), nm, (suffix or "").upper().strip())


def parse_freeform(raw: str):
    """Pull number / direction / street / suffix / city out of a project address."""
    toks = [t for t in re.split(r"[^0-9A-Z]+", (raw or "").upper()) if t]
    if not toks or not toks[0].isdigit():
        return None, None
    num, rest = toks[0], toks[1:]
    direction = rest.pop(0) if rest and rest[0] in DIRECTIONS else ""
    sfx_at = next((i for i, t in enumerate(rest) if t in SUFFIXES), None)
    if sfx_at is None:
        return make_key(num, direction, " ".join(rest[:1]), ""), ""
    name = " ".join(rest[:sfx_at])
    suffix = rest[sfx_at]
    tail = [t for t in rest[sfx_at + 1:] if not t.isdigit()]
    city = " ".join(tail)
    return make_key(num, direction, name, suffix), city


def project_keys(p: dict):
    apn = norm_apn(p.get("apn", ""))
    key, city = parse_freeform(p.get("address") or p.get("name") or "")
    return apn, ({key} if key else set()), city


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("csv_path")
    ap.add_argument("--projects", default=str(DEFAULT_PROJECTS))
    ap.add_argument("--all", action="store_true", help="also list unmatched export rows")
    args = ap.parse_args()

    projects = json.loads(Path(args.projects).read_text())["projects"]
    index = [(p, *project_keys(p)) for p in projects]

    with open(args.csv_path, newline="", encoding="utf-8-sig") as fh:
        rows = [r for r in csv.DictReader(fh) if (r.get("Permit Number") or "").strip()]

    hits: dict[str, list] = {}
    unmatched_rows = []
    for r in rows:
        apn = norm_apn(r.get("Parcel Number", ""))
        key = make_key(r.get("Number", ""), r.get("Prefix Direction", ""),
                       r.get("Street Name", ""), r.get("Suffix Street Type", ""))
        city = (r.get("City") or "").upper().strip()
        for p, papn, pkeys, pcity in index:
            apn_hit = bool(papn and apn and papn == apn)
            addr_hit = bool(key and key in pkeys and (not pcity or not city or pcity == city))
            if apn_hit or addr_hit:
                hits.setdefault(p["name"], []).append(r)
                break
        else:
            unmatched_rows.append(r)

    print(f"export rows: {len(rows)}   projects in registry: {len(projects)}")
    print(f"matched rows: {len(rows) - len(unmatched_rows)}   ignored (not ours): {len(unmatched_rows)}\n")

    if hits:
        for name, rs in hits.items():
            print("=" * 78)
            print(name)
            print("=" * 78)
            for r in rs:
                for col in SHOW:
                    v = (r.get(col) or "").strip()
                    if v:
                        print(f"   {col:<28} {v}")
                print()
    else:
        print("No export row matched any project in the registry.\n")

    covered = set(hits)
    missing = [p for p in projects if p["name"] not in covered]
    print(f"projects with NO match in this export: {len(missing)}")
    for p in missing:
        print(f"   - {p['name']}"
              + (f"   [APN {p['apn']}]" if p.get("apn") else "   [no APN on record]"))

    if args.all and unmatched_rows:
        print(f"\nunmatched export rows ({len(unmatched_rows)}):")
        for r in unmatched_rows:
            street = " ".join(x for x in (r.get("Prefix Direction"), r.get("Street Name"),
                                          r.get("Suffix Street Type")) if x)
            print(f"   {r['Permit Number']:<22} {r.get('Number','')} {street}, {r.get('City','')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
